name: Build README
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          # necessary for github-action-til-autoformat-readme
          fetch-depth: 0
      - name: Autoformat README
        uses: cflynn07/github-action-til-autoformat-readme@1.2.0
        with:
          description: |
            오늘 학습한 내용을 정리하는 공간입니다. 날짜 기준으로 정리한 레거시 TIL은 더 이상 운영하지 않고, 이 저장소로 이관중입니다. 이 곳에서 작성한 글들을 바탕으로 [블로그][1] 포스팅을 작성하고 있습니다.
          footer: |
            [1]: https://yangeok.github.io/
          list_most_recent: 10 # optional, lists most recent TILS below description
          date_format: "2006-01-02T15:04:05Z07:00" # optional, must align to https://golang.org/pkg/time/#Time.Format
